### ISSUE TITLE
Implement reversing an array

### ISSUE THREAD

**Issue by bennett1412** [DSCCUSAT/Data-Structures-and-Algorithms#1]
- [ ] Python
- [ ] C
- [ ] C++
- [ ] Kotlin
- [ ] Java
- [ ] JavaScript

Add the file [here](https://github.com/DSCCUSAT/Data-Structures-and-Algorithms/tree/main/arrays/reverse-array)

**Comment by Meghwantsingh** [comment]
Hello again,
sorry but could you assign this work also.
