### ISSUE TITLE
Implement Bubble Sort

### ISSUE THREAD

**Issue by bennett1412** [DSCCUSAT/Data-Structures-and-Algorithms#2]
- [ ] Python
- [ ] C
- [ ] C++
- [ ] Kotlin
- [ ] Java
- [ ] JavaScript

Visit here [here](https://github.com/DSCCUSAT/Data-Structures-and-Algorithms/tree/main/arrays/sorting/bubble-sort)

**Comment by Meghwantsingh** [comment]
Hi,
I would like to work on this.

**Comment by ASHWIN776** [comment]
Hello, 
you are welcome to work on this
